### ISSUE TITLE
version from Mai 5th - wont stop transmitting

### ISSUE THREAD

**Issue by whallmann** [EngineerGuy314/pico-WSPRer#12]
Hi Rob, your fresh repair about the frequency hopping looks very good.
But there are some things i need your help.
So the TX wont stop transmitting now. Is this ok?
Callsign: DF7PN
Suffix: -
ID13: Q4
Minute 4
Lane: 3

Later i tried Suffix: 3
This doesn´t matter.

**Comment by EngineerGuy314** [comment]
>>So the TX wont stop transmitting now. Is this ok?

not sure if technically that is "ok", but right or wrong it is by design.

I was seeing a measurable change in chip temperature as the transmissions started and stopped. I now keep the TX "idling" to keep the board temperature more uniform.  This feature might no longer be needed, and might not even be legal. But I am going to keep it in the code for now.

Stopping the transmition was also causing a problem when testing with a resistive dummy load.  Since the two outputs were antiphase, when it stopped one would be high and the other low, causing a large DC current drain into the load. Since the outputs are better at DC then RF, current consumption was actually INCREASING when the TX stopped.
