### ISSUE TITLE
Feature proposal: GPS shutdown - wakeup

### ISSUE THREAD

**Issue by IU5HKU** [EngineerGuy314/pico-WSPRer#47]
First thing first: thanks for this great piece of code, it works like a charm. After that i have a proposal, why not send the shutdown command to the gps module to improve the sleepmode? Ublox gps and compatible chips can be put in a "backup mode" where it consume very little current, stated below 200uA, not bad at all. Can be also waked up from this state simply writing some chars over the serial, it needs only some form of "activity" to wake up and do an hot start, so it could retrieve and track satellites from the "backup" mode very quickly, way less than a complete cold start from power off.
you can use simple serial communication to send the "sleep" command to the gps chip, i've read this many years ago...i'll try to retrieve where....here it is:

[Arduino forum thread about GPS commands](https://forum.arduino.cc/t/gps-module-power-management/477859/15)

as you can read is simply matter to send an array of byte, and all the uBlox chips and compatible ones with this command will goes in a sort of "deep sleep".
Hope this can help, thank you for your time, have a nice day!

**Comment by EngineerGuy314** [comment]
Glad you are finding the code useful!
Original versions of the software did completely remove power to the GPS module while transmitting.  this did work, sortof, but it was very prone to excessive frequency drift due to changing temperature. And even in the conditions of a high altitude balloon flight temperatures can change enough over  the course of a two minute WSPR transmission to excessively skew the frequency. so the GPS needs to stay on continually to provide the PPS timing signal, which is used by the PICO every second to adjust it's frequency compensation. 

I suppose if the pico was covered in some insulation its temperature would not change rapidly enough to cause drift problems. Or, while the gps is off, you could look at the onboard temperature sensor, and try to compensate frequency based on that. At one point i was doing just that. It was very finicky, i abandoned that feature.

I do have a "low power battery" mode which only transmits once an hour, and keeps the gps fully powered down (and the pico in sleep mode) when not xmitting. but thats not really what you were suggesting...

**Comment by IU5HKU** [comment]
Yes, i know that when you transmit you need the gps powered on, for the pps signal, you need that precise signal for count and correct the generated frequency as needed, but my proposal isn't for the "flight mode", but the "standalone beacon mode", when you transmit one beacon every 10 minutes. Often this kind of "ground" beacons are battery or solar operated, and to minimize battery drainage is a plus. I was thinking about using this technique of "gps deep sleep" between two consecutive transmissions, when you don't need the gps to be powered on. Think about this as a smarter beacon mode, to use when you are not at home, to test an antenna in a particular place, or similar.
Anyway, my idea was only a suggestion to improve this already great code, i can only say thanks for what you have done since now, great work indeed
